version: '3'

networks:
  devnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.8.0/24

services:
  debug1:
    container_name: debug1
    hostname: debug1
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: liuempire/siphon_datapath_debug
    security_opt:
      - seccomp:unconfined
    ports:
      - "7776:22"
    volumes:
      - ..:/home/debugger/code
    networks:
      devnet:
        ipv4_address: 172.16.8.2
    working_dir: /home/debugger/code

  debug2:
    container_name: debug2
    hostname: debug2
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: liuempire/siphon_datapath_debug
    security_opt:
      - seccomp:unconfined
    ports:
      - "7777:22"
    volumes:
      - ..:/home/debugger/code
    networks:
      devnet:
        ipv4_address: 172.16.8.3
    working_dir: /home/debugger/code

  debug3:
    container_name: debug3
    hostname: debug3
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: liuempire/siphon_datapath_debug
    security_opt:
      - seccomp:unconfined
    ports:
      - "7778:22"
    volumes:
      - ..:/home/debugger/code
    networks:
      devnet:
        ipv4_address: 172.16.8.4
    working_dir: /home/debugger/code
